# Generated by Django 5.2.12 on 2026-04-14 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=50)),
                ('service_name', models.CharField(max_length=255)),
                ('package_id', models.CharField(max_length=50)),
                ('package_name', models.CharField(max_length=255)),
                ('package_sessions', models.CharField(max_length=100)),
                ('package_price', models.CharField(max_length=100)),
                ('package_result', models.TextField()),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('status', models.CharField(choices=[('confirmed', 'Da xac nhan'), ('pending', 'Cho xac nhan'), ('cancelled', 'Da huy')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'db_table': 'appointments',
                'ordering': ['appointment_date', 'appointment_time'],
                'constraints': [models.UniqueConstraint(fields=('appointment_date', 'appointment_time'), name='unique_appointment_slot')],
            },
        ),
    ]
