# Generated by Django 5.2.12 on 2026-04-14 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='Tư vấn dịch vụ', max_length=255)),
                ('status', models.CharField(choices=[('open', 'Dang mo'), ('closed', 'Da dong')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consultation Conversation',
                'verbose_name_plural': 'Consultation Conversations',
                'db_table': 'consultation_conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('customer', 'Khach hang'), ('spa', 'Spa')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.consultationconversation')),
            ],
            options={
                'verbose_name': 'Consultation Message',
                'verbose_name_plural': 'Consultation Messages',
                'db_table': 'consultation_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
